# Generated by Django 5.0.13 on 2025-04-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where this item should be stored (e.g., 'Pantry', 'Fridge', 'Freezer')",
                max_length=100,
                null=True,
            ),
        ),
    ]
